### ISSUE TITLE
Looking for feedback on the documentation!

### ISSUE THREAD

**Issue by steven-terrana** [jenkinsci/templating-engine-plugin#103]
What do you wish was better about the [documentation](https://boozallen.github.io/sdp-docs/jte/1.7.1/index.html)?

**Comment by mfuxi** [comment]
I believe the most important is: simple examples for popular scenarios and usecases and especially  **Kubernetes** and **OpenShift** use cases since these platforms are becoming more and more popular as time passes

**Comment by pniederlag** [comment]
Seems documentation was updated to prerelease-2.0 meanwhile https://boozallen.github.io/sdp-docs/jte/prerelease-2.0/index.html

After digging into the documentation I believe to have a good overview of JTE. I found myself to quickly get around and find pieces I was looking for pretty quick. 

I am a little puzzled that adoptors is not really populated yet. 

Now asking myself:

- I'd like to stick with the practice of having a Jenkinsfile in my source repos, and dislike adding "arbitrary" *.groovy files to my java, ruby, php and xxx projects... Would it be possible to stick with having a Jenkinsfile (which is some groovy DSL anyway) and make use of JTE in there?

**Comment by steven-terrana** [comment]
hey @pniederlag!  Here's the docs page on [Pipeline Template Selection](https://boozallen.github.io/sdp-docs/jte/1.7.1/governance/pipeline_template_selection.html).   Unless you explicitly disable repository Jenkinsfiles by setting `allow_scm_jenkinsfile = false`, they will be used as the pipeline template and be able to use JTE in there. 

If you have more questions, i'd love to talk about them in the [Gitter Channel](https://gitter.im/jenkinsci/templating-engine-plugin).

Thank you!
