### ISSUE TITLE
Prioritize conflicting libraries according to governance level

### ISSUE THREAD

**Issue by yoav-klein** [jenkinsci/templating-engine-plugin#124]
Consider the following scenario:
You have this pipeline_config.groovy file in the System Configurations of Jenkins:
```
// pipeline_config.groovy
libraries {
  ansible
  sonarqube
  ... // other common libraries used by virtually all the teams in the organization
}
```
And the `sonarqube` library contains the `static_code_analysis.groovy` step

Now, some teams use klockwork for static code analysis. So we'd want to have a `klockwork` library that will also contain a `static_code_analysis.groovy`. But how do we let this team to use the klockwork library?
We can set `override = true` in the global configuration file, and let the team define their own `libraries` block. But then they'll have to define all the other libraries that are in the global `libraries` block. 
If we set `merge = true`, once the `static_code_analysis()` step will be called from that team's template a collision will raise obviously. <br>

My suggestion is to add functionality so that upon a collision in which we have two libraries define the same step, but these two libraries are in two different levels, the most specific will be chosen.

**Comment by steven-terrana** [comment]
Thanks for the feature idea! 

Have you considered breaking up your configuration hierarchy a bit more to support this? 

You could solve this by removing **both** sonarqube and klockwork from the common pipeline configuration used by all the apps. 

from there, you could create another governance tier that adds the sonarqube configuration for most apps.

for the teams that use klockwork, those jobs could live outside the tier that defines sonarqube. 

## Namespacing

As part of JTE 2.0 we're implementing primitive namespacing to solve pieces of this problem.  so when that is released, you would be able to load both libraries and in your template (or another library) you could call `jte.libraries.sonarqube.static_code_analysis()` and `jte.libraries.klockwork.static_code_analysis()`. 

once that exists, there are a few design patterns you could use to proxy calls to static code analysis based upon a "resolution" configuration you define in the pipeline configuration and access via the `pipelineConfig` variable.

**Comment by yoav-klein** [comment]
Hi Steven, Thanks for the response!

Breaking up the configuration hierarchy would definitely work, although that would force me to create a folder hierarchy based on the tools used which is not so great, at least in my organization. 
Take this scenario for example and tell me what you think: Say I want to have the following template:
```
    // some code
    setProperties() 
   // some code
```

I want to have a step of `setProperties()` so that each project could set it's own properties of the Job, such as triggers, parameters, etc.  So I want to enable each project to provide its own implementation of this step, but I also want to enable them not to provide an implementation, by providing a general implementation that just does nothing in the higher tier. If the lower tier's step would override the higher tier, it would be fantastic. Do you have a better idea to implement this?

Another question if you may: Say I have a library, which uses a bunch of configurations from the `pipeline_config.groovy`, such as:
```
libraries {
   artifactory {
     url = "http://myUrl"
     repo = "MyProject"
     source = "artifact.out"
  }
}
``` 

Let's say I have a bunch of projects using the same Artifactory (and possibly the same repo), but each uploads its own artifacts obviously. From my try & error, I couldn't define some configurations in the lower tier (source) and another in the higher (url, etc.). Do you have any idea, or could that be a feature?

**Comment by cokieffebah** [comment]
@yoav-klein regarding the artifactory lib ... I don't think this is pertinent to 'conflicting libraries' but, ... you can make the artifactory block `
libraries{
  artifactory{
     override = true // now lower project/tiers can change the values set in this block by the current tier
     merge = true // lower projects/tiers can add new properties
     url = "http://ArtifactoryURL"
     repo = "MyProject"
     source = "artifact.out"
  }
}
`

**Comment by cokieffebah** [comment]
piggybacking on a suggestion steven made:
use a config like below for your higher governance tier, then change the 'projectSpecific' block in your jobs or lower tiers
```
libraries{
  artifactory{
     projectSpecific{
         override = true
         merge = true
     }
     url = "http://ArtifactoryURL"
     repo = "MyProject"
     source = "artifact.out"
  }
}
```
