### ISSUE TITLE
For 2.0 add warning if no steps directory is in a library

### ISSUE THREAD

**Issue by cokieffebah** [jenkinsci/templating-engine-plugin#125]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request
change LibraryProvider.hasLibrary implementations to report if no `steps` directory is present and return false
“Library ${libName} exists but does not have a steps directory. No steps will be loaded.”

**Comment by cokieffebah** [comment]
@steven-terrana do you want it to just check if steps directory exists or also if it has any *.groovy files in steps

**Comment by steven-terrana** [comment]
should warn if there are no `*.groovy` files in the `steps` directory since the warning is probably "No steps present for library ${libName}."

**Comment by cokieffebah** [comment]
ok.  adding the warning output to the implementations of LibraryProvide.hasLibrary.  as previously discussed, hasLibrary will return false if the library does not have a steps directory and print a warning. Based on this feedback, I will also make hasLibrary return false and print the same warning if a steps directory exists, but does not have a step.
