### ISSUE TITLE
Allow using JTE from SCM for pipeline jobs

### ISSUE THREAD

**Issue by gpaciga** [jenkinsci/templating-engine-plugin#128]
### Feature Request

I would like to be able to configure standalone pipeline jobs using the Templating Engine from SCM.

Like the "Pipeline script from SCM option", I should be able to configure the SCM repo, branch, and the path to the Jenkinsfile to execute.

As it is currently, I essentially have to implement two interfaces for any functionality that I want available to both multibranch pipelines that use JTE and standalone pipelines. As a result, most of my JTE libraries are just wrappers around other functionality, aliasing a tool-aware function name (e.g. "mytool.unit_test()") with a tool-agnostic one ("unit_test()"), with some extra handling to pass in arguments from the library config in pipeline_config.groovy. Then, people writing Jenkinsfiles have to be aware of which version of the interface they have to use depending on whether they're writing a multibranch job or not.

There is some version of support for this by essentially copy-pasting a Jenkinsfile into the UI, but obviously it is preferable for jobs to be managed by SCM.

**Comment by cokieffebah** [comment]
We are currently working this as issue #100. Closing this as a duplicate. If we have misunderstood this request let us know

**Comment by gpaciga** [comment]
Thanks, sorry the comments on that one threw me off, didn't read carefully enough.

**Comment by cokieffebah** [comment]
understood, the additional comments generated some additional behavior to what you are requested
