### ISSUE TITLE
How to apply team's implementation of libraries in current workspace?  similar to pipeline_config,

### ISSUE THREAD

**Issue by trqlcgcg** [jenkinsci/templating-engine-plugin#144]
### Your checklist for this issue

🚨 Please review the [Support Policy](https://github.com/jenkinsci/.github/blob/master/SUPPORT.md)

- [ ] The question was asked in the project's [Gitter chat](https://gitter.im/jenkinsci/templating-engine-plugin)
- [x ] Jenkins version - 2.252
- [ x] Plugin version - 2.0
- 

### Description

Please describe your issue here, and explain what you have already tried to resolve it.

I would like the app team to provide the implementation of build() and unit_test() in the pipeline.   I added libraries folder to the application repo and added maven as a library with the forementioned methods.   

WITHOUT configure JTE the mutli-branch pipeline,  is there a way for JTE to automatically search the current workspace and process the libraries in the libraries folder?  Similar to how it would process the pipeline_config.groovy in the current workspace?

**Comment by trqlcgcg** [comment]
For example,  in a multi-branch pipeline,  I would like to be able to change a build script (maven.build) for a feature branch of the application.   If the only way is to configure the libraries is from a single branch at the multi-branch configuration, I would be forced to use the same build script implementation for all branches of the application.

**Comment by cokieffebah** [comment]
these should be posted to the gitter channel: https://gitter.im/jenkinsci/templating-engine-plugin: " The question was asked in the project's Gitter chat"
