### ISSUE TITLE
Argument for a stage is cast to Map which breaks with ApplicationEnvironments

### ISSUE THREAD

**Issue by LMojica** [jenkinsci/templating-engine-plugin#151]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version
2.263.1
- [x] Plugin version
2.0
- [x] OS
Centos 7

### Description
In version 2.0, arguments that are passed to a Stage are cast to a Map before the argument is passed to the Steps (see https://github.com/jenkinsci/templating-engine-plugin/blob/release/2.0/src/main/resources/org/boozallen/plugins/jte/init/primitives/injectors/Stage.groovy#L53-L57). This causes problems when passing an ApplicationEnvironment as an argument because it can't be cast to a Map, so Groovy casts it to a Proxy.

In previous versions, such as 1.7.1, the stage argument was passed through to the steps without any modification. I believe this is a regression, but if this change is intentional, could you describe how we should pass the ApplicationEnvironment to steps within a stage?

**Comment by cokieffebah** [comment]
The change was intentional but we missed this issue in our testing.  We will work to resolve this issue.  Thanks for bringing this to our attention

**Comment by cokieffebah** [comment]
I think you mentioned this in the gitter channel.

**Comment by cokieffebah** [comment]
reading the gitter comments appears to be an issue with the other parts of the users code.  Closing this issue
