### ISSUE TITLE
Jenkinsfile-runner support

### ISSUE THREAD

**Issue by FLavalliere** [jenkinsci/templating-engine-plugin#156]
We would like to run the JTE with 'pre-downloaded' files (locally) mounted into a specific docker volume 

ie mounting the JTE Git repo inside somehting like /local/jte and /local/libraries

Using the jCas to configure the jenkinsrunner to know where to load the JTE Jenkins / pipeline_confi.groovy.

Then we could simply run the Jenkinsfile-runner docker on our repository to test the Jenkins pipeline. This would help to develop locally.

**Comment by steven-terrana** [comment]
I started looking into this, this comment is mostly to give you a status update and take some notes for myself for when i get a chance to come back to this (or for someone else that wants to take this the rest of the way):

## Library Source

Passing in libraries would already be accomplishable by mounting a directory that is a local git repo (`git init` has been run) and then configuring the library source via the file URL protocol.  

something like:
> docker run -v my-libraries:/local/my-libraries jenkins/jenkins:lts.........

and then specifying the library source as `file:///local/my-libraries`. 

As long as the `my-libraries` directory has the files committed, it oughta work as expected.  There does not need to be a remote repository, but the directory does have to be a local git repo and the files do have to be committed locally. 

removing the dependency on having the directory be a local git repository would require a new `LibaryProvider` extension for the file system.  currently, only SCM and Plugin are supported. 

## Jenkinsfile Runner Feature Updates

To get the Jenkinsfile Runner to know about JTE, one would have to create a [PipelineDefinitionProvider](https://github.com/jenkinsci/jenkinsfile-runner/blob/master/payload/src/main/java/io/jenkins/jenkinsfile/runner/PipelineDefinitionProvider.java) similar to what was done for the Pipeline as YAML plugin: https://github.com/jenkinsci/jenkinsfile-runner/pull/463

i would probably recommend that command line flags be added to the jenkinsfile-runner command to allow passing in the pipeline template && the pipeline configuration, but you could also skip the pipeline configuration flag by configuring it as a governance tier via JCasC.

**Comment by steven-terrana** [comment]
https://github.com/jenkinsci/jenkinsfile-runner/pull/477
