### ISSUE TITLE
Add/Fix Resumeability unit testing

### ISSUE THREAD

**Issue by cokieffebah** [jenkinsci/templating-engine-plugin#160]
### Use Case

Need to have test(s) for Pipeline restarts/resume.  The current/'recently added' tests are need to be fixed

**Comment by steven-terrana** [comment]
to add some detail to this, when restarting a JTE pipeline via the `RestartableJenkinsRule`,  an assertion error is thrown by [CpsThreadGroup](https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java#L176) during rehydration that fails the pipeline. 

I can't reproduce this with an actual Jenkins instance.
