### ISSUE TITLE
Translate environment variables in branch name for SCM provided config files

### ISSUE THREAD

**Issue by rayvincent2** [jenkinsci/templating-engine-plugin#165]
### Use Case

I'm trying to build my pipeline to pull the parameterized branch source and leverage JTE to run my build scripts.  When I configure JTE to look for the pipeline_config.goovy in SCM, I can get to work perfectly if I specify the branch I want to build exactly.  I'd like for JTE to translate the environment variables specified in the branch name so that I can target any branch I'd like by using parameters.  I've had great success doing this with standard Jenkinsfile pipelines in SCM, but it does not look like JTE supports this.

Here's how I have my project configured:
- Parameter: BRANCH_SOURCE
- Pipeline Definition: Jenkings Templating Engine
  - Pipeline Configuration: From SCM
    - Source Location: Git
      - Repositories: xxxx.git
      - Branches to Build: */${BRANCH_SOURCE}

### Feature Request

Support translating environment variables in the branch name before connecting to the remote repository

**Comment by rayvincent2** [comment]
Currently when I build I get this error:
```
[JTE] pipeline_config.groovy does not exist. (show)
[JTE] hudson.plugins.git.GitException: Command "git fetch --tags --progress --prune origin +refs/heads/${BRANCH_SOURCE}:refs/remotes/origin/${BRANCH_SOURCE}" returned status code 128: 
[JTE] stdout: 
[JTE] stderr: fatal: Couldn't find remote ref refs/heads/${BRANCH_SOURCE}
[JTE] Unexpected end of command stream
...
```

**Comment by steven-terrana** [comment]
That would be useful! Unfortunately, by the time JTE receives those configurations it's already in the form of a `GitSCM` object from the git-plugin and JTE just uses the SCM API to fetch contents from the repository. 

so i'm _pretty sure_ this is a feature request for the git plugin to do environment expansion when parsing the BranchSpecs.

**Comment by steven-terrana** [comment]
hmm, i do see that the documentation claims to support the `${ENV_VAR}` syntax.  i'll dig into a bit.

**Comment by steven-terrana** [comment]
I've run out of code spelunking time for today but my current theory is that the **[GitSCMFileSystem](https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/jenkins/plugins/git/GitSCMFileSystem.java)** `build` methods don't do environment expansion on the branch specs?

**Comment by rayvincent2** [comment]
Aha, it looks like the `checkout` method of GitSCM is what does it automatically.  I'll do some spelunking myself to see how it can possibly be leveraged in this project.  This would be an enormous help for my use case.

[GitSCM.checkout:1328](https://github.com/jenkinsci/git-plugin/blob/5edc26da3bd4962bdb8599ef1cbc40d335cd1129/src/main/java/hudson/plugins/git/GitSCM.java#L1328) -> [getParamLocalBranch:484](https://github.com/jenkinsci/git-plugin/blob/5edc26da3bd4962bdb8599ef1cbc40d335cd1129/src/main/java/hudson/plugins/git/GitSCM.java#L484) -> [getParameterString:600](https://github.com/jenkinsci/git-plugin/blob/5edc26da3bd4962bdb8599ef1cbc40d335cd1129/src/main/java/hudson/plugins/git/GitSCM.java#L600) -> [EnvVars.expand](https://javadoc.jenkins-ci.org/hudson/EnvVars.html#expand-java.lang.String-)

**Comment by rayvincent2** [comment]
I did plenty of digging and see how the SCM API is leveraged in JTE.  I agree with your instinct that adding environment variable expansion in GitSCMFileSystem would be the way to go.

**Comment by rayvincent2** [comment]
I've found the issue on the Jenkins issue tracker that will solve this.  I'm going to see how far I can take this:
https://issues.jenkins.io/browse/JENKINS-60630

**Comment by steven-terrana** [comment]
appreciate the help here @rayvincent2!

**Comment by rayvincent2** [comment]
I've created a PR on git-plugin here: https://github.com/jenkinsci/git-plugin/pull/1040

I've tested the build on my local Jenkins server using JTE and it works great!  The only problem is the potential race condition I mentioned in the PR regarding determining the currently running build.

Here's the latest build if anyone else wants to test it out:
https://ci.jenkins.io/job/Plugins/job/git-plugin/view/change-requests/job/PR-1040

**Comment by steven-terrana** [comment]
@rayvincent2 - really appreciate you stepping up to fix issues beyond just reporting them!  it's a huge help. 

I'm going to go ahead and close this issue and if there are still issues after jenkinsci/git-plugin#1040 then we can re-open
