### ISSUE TITLE
No such property: any for class: WorkflowScript

### ISSUE THREAD

**Issue by mdeitrick** [jenkinsci/templating-engine-plugin#181]
### Environment Information

- [x] Jenkins version (2.222.1-cb-7)
- [x] Plugin version (2.0.3)
- [x] OS (RHEL 7)

### Description

I am working on creating a pipeline using declarative syntax that leverages JTE and I'm running into an issue where the property `any` does not exist.  Also, the stack trace in the console output points directly to the line `agent any`.  I'd also like to note that version 1.5.1 of [pipeline-model-definition-plugin](https://github.com/jenkinsci/pipeline-model-definition-plugin) is installed.

#### Pipeline

````groovy
pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '15', artifactNumToKeepStr: '15'))
        disableConcurrentBuilds()
        timeout(time: 1, unit: 'HOURS')
    }
    stages {
        // ...
    }
}
````

#### Console Output

`hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: any for class: WorkflowScript`

As an aside, changing `agent any` to `agent ""` produces the following error.

`java.lang.NoSuchMethodError: No such DSL method 'agent' found among steps [...]`

And removing `agent any` altogether produces the following error.

`java.lang.NoSuchMethodError: No such DSL method 'options' found among steps [...]`

**Comment by mdeitrick** [comment]
As I read through the other posts for this plugin I am wondering if the issue stems from an outdated version of the pipeline-model-definition plugin.  Looks like we'll need to upgrade to [v1.8.0](https://github.com/jenkinsci/pipeline-model-definition-plugin/releases/tag/pipeline-model-definition-1.8.0)... now to figure out why the option for upgrading is greyed out!  :thinking:

**Comment by steven-terrana** [comment]
Hey @mdeitrick , that's definitely the issue!  Going to close this. Feel free to reopen if you still experience issues after upgrading.
