### ISSUE TITLE
template_methods  block seems not working

### ISSUE THREAD

**Issue by ravindrakmr** [jenkinsci/templating-engine-plugin#189]
### Environment Information

- [2.249.3] Jenkins version
- [2.0.4] Plugin version
- [ Windows 10] OS

### Description

I am new to JTE and trying to play around it. I am able to make it work on my Jenkins but somehow template_methods block is not working as expected. I am just trying to invoke unit_test step from the template but it is invoking all steps. here is my template -
build()
unit_test()
static_code_analysis()

and here is my pipeline configuration file -
template_methods{
  unit_test
}
libraries{
    gradle
    sonarqube
}

output -
![image](https://user-images.githubusercontent.com/50581150/112472930-b61d1400-8d93-11eb-9bfb-101e442d203a.png)

Am I missing anything here ? I am using library source from SCM.

**Comment by cokieffebah** [comment]
I suspect you have a 'unit_test' in your 'gradle' library.  if I remember correctly, 'template_methods' are basically placeholders and any actual steps would override your template_methods.unit_test

**Comment by ravindrakmr** [comment]
@cokieffebah thanks for looking into this. Yes unit_test is inside the gradle library.  Basically my requirement is I dont want to run all the steps of the pipeline template, so do we have a way by which we can limit the number of steps that need to execute in pipeline config file ?

**Comment by cokieffebah** [comment]
hmm, thats an interesting problem.  How are deciding which steps are run? Normally the pipeline template defines which steps should be run

**Comment by ravindrakmr** [comment]
Correct , in normal scenarios we are supposed to execute the steps given in the template but lets say if we have same template for UI and Java where we don't need to execute step lint or npm_install for java, in this type of scenario we may need to skip certain steps. However, there is way of passing Boolean keyword and skip that step but that looks not so clean approach.

**Comment by cokieffebah** [comment]
template_method was probably the right direction.  Just make sure the libraries used don't have the step you want to skip.
java_project/pipeline_config.groovy:
```
libraries{
   java // does not have npm_install step
}

template_methods{
  npm_install
  }
  ```
  
 npm_project/pipeline_config.groovy:
```
libraries{
   npm // does not have java_thin step
}

template_methods{
  java_thing
  }
  ```
  
  Jenkinsfile:
  ```
  prepare()
  build()
  npm_install()
  java_thing()
  unit_test()
  scan()
  deploy()
  ```

**Comment by cokieffebah** [comment]
or you can 'implement' those steps but make them blank/empty/no-op:
java/npm_install.groovy:
```
void call(){}
```

in this case the step name should probably be more generic like `pre_build`

**Comment by ravindrakmr** [comment]
ok makes sense. Thanks for the suggestion.
