### ISSUE TITLE
Unable to resolve class from external shared library in library step

### ISSUE THREAD

**Issue by mdeitrick** [jenkinsci/templating-engine-plugin#216]
### Environment Information

- [x] Jenkins version (2.263.2-cb-2)
- [x] Plugin version (2.1)
- [x] OS (Redhat Linux)

### Description

One of our library steps developed has a dependency on vars and classes within a shared library.  I've tried importing the library multiple ways and discovered that implicitly loading the shared library at a global level is the only way to resolve the issue.  I think this will create some issues down the road since folks might need ways to override the global shared library to test their changes.  Not to mention, not all pipelines will need to reference this particular shared library when they're kicked off.

#### Steps to reproduce

Include a reference to the shared library in a JTE library step.

```groovy
@Library('shared-library') _

import com.acme.Clazz
```

Results in...

```
ERROR: Could not find any definition of libraries [shared-library]
[JTE] Failed to parse step text. Library: abc. Step: def.
[JTE] startup failed: (show)
org.boozallen.plugins.jte.util.AggregateException: The following errors occurred: 
1: startup failed:
WorkflowScript: Loading libraries failed
```

or

```groovy
library 'shared-library'

import com.acme.Clazz
```

Results in...

```
[JTE] Failed to parse step text. Library: abc. Step: def.
[JTE] startup failed: (show)
org.boozallen.plugins.jte.util.AggregateException: The following errors occurred: 
1: startup failed:
WorkflowScript: 5: unable to resolve class com.acme.Clazz
 @ line 5, column 1.
   import com.acme.Clazz
   ^
```

This could very well be a case of me not fully understanding how these library constructs work, or something else external to JTE.  But I figured I would submit this issue in the event something can be done within JTE.

**Comment by steven-terrana** [comment]
on first pass, i was able to get it working by putting an `@Library` annotation in the step itself. 

I realize this isn't ideal, but it's a temporary work around while we figure out if it's possible to fix. 

The challenge is that each step is compiled separately, and the way `@Library` works is by updating the classpath at compile time. 

i'll see what's possible but it's going to take some time. 

In general, i wouldn't recommend mixing Jenkins Shared Libraries and JTE libraries.

**Comment by steven-terrana** [comment]
just a note to self (or anyone else that wants to try and fix):

might be able to fix this by:
1. adding a dependency on workflow-cps-global-lib to JTE
2. Updating `StepWrapperFactory.prepareScript` to iterate over `ExtensionList.lookup(ClassPathAdder)` to pass the step's CpsFlowExecution to the adder to update the classpath.

**Comment by steven-terrana** [comment]
I made a global shared library that had a file `src/org/foo/Bar.groovy`

and then my step was:

``` groovy
@Library("my-shared-library")
import org.foo.Bar

void call(){
  Bar.doThing(steps)
}
```

**Comment by mdeitrick** [comment]
> I made a global shared library that had a file `src/org/foo/Bar.groovy`
> 
> and then my step was:
> 
> ```groovy
> @Library("my-shared-library")
> import org.foo.Bar
> 
> void call(){
>   Bar.doThing(steps)
> }
> ```

Yep, I tried the same thing and ended up seeing the message `ERROR: Could not find any definition of libraries [shared-library]`.  For shared library configuration, did you happen to check "Load implicitly" or do anything special for that library entry?

**Comment by steven-terrana** [comment]
i did not.  I tried from both a pipeline template and from a library step and both worked okay. 

I would really recommend migrating from a global shared library to a JTE library. 

Upon further digging, it's actually not possible (with pretty significant refactoring) to have an `@Library` annotation in a pipeline template update the classpath of a library step.

This is because at the point that JTE library steps are being compiled, the template hasn't even been determined yet (and therefore hasn't been compiled).

It's doubtful support will be added for mixing shared libraries and JTE given JTE's library functionality has most of the same capabilities that shared libraries do.

**Comment by mdeitrick** [comment]
Understood, thanks for taking a look.  I think we'll be able to implement a workaround for our particular use case, since this shared library is technically "owned" by another group in our company.
