### ISSUE TITLE
Using JTE to specify the cloud provider yaml in kubernetes environment to spawn agents dynamically

### ISSUE THREAD

**Issue by touseefspeaks** [jenkinsci/templating-engine-plugin#219]
### Environment Information

- [x] Jenkins version :2.77.4
- [x] Plugin version : 2.2.2
- [x] OS: linux

I have jenkins infrastructure running in k8s environemnt. I would like to leverage the JTE to spawn agent dynamically
Normally in jenkins file we do something like
```
pipeline {
    agent {
        kubernetes {
            yamlFile 'CI/cloudprovider.yml'
            defaultContainer 'main'
        }
    }
    -------
Can you provide me any pointer how to do something similar in conjunction with JTE.
In JTE we define jenkinsfile in some config repo like 
```
build()
static_code_analysis()

I tried something like below for using JTE with declarative pipeline
where build () is the repo defined libraries folder 

```
pipeline {
   agent {
       kubernetes {
           yamlFile 'cloudProvider.yaml'
       }
   }
  stages {
    stage("example") {
      steps {
    script{
        build()
     }
      }
    }
  }
}
```
 It ended up with the error, even though  i have the cloudprovider.yaml in workspace parallel to jenkins file . However the same jenkinsfile works perfectly and invokes clouprovider.yaml if JTE is not used  
```
java.io.FileNotFoundException: URL: /rest/api/1.0/projects/JTE/repos/test-jte1/browse/cloudProvider.yaml?at=master&start=0&limit=500
 	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:866)
 	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1162)

**Comment by steven-terrana** [comment]
this is likely a bug with the [BitBucket Branch Source Plugin](https://github.com/jenkinsci/bitbucket-branch-source-plugin).

I tested this with GitHub and it worked as expected. 

JTE has nothing to do with how the declarative pipeline's `agent` directive works nor how the kubernetes plugin interacts with that functionality.
