### ISSUE TITLE
[Enhancement]: Steps with lifecycle hook annotation gets executed after any method of conditional step

### ISSUE THREAD

**Issue by krichter722** [jenkinsci/templating-engine-plugin#223]
### Jenkins Version

2.306

### JTE Version

2.3

### Bug Description

I have a step `test_extension` with a lifecycle annotation for conditional execution:

```
@AfterStep({ hookContext.step == "test" })
void call() {
    // so something after test....
}
```

In my governance tier I'm using `test()` which is defined somewhere and loaded with a `void call()` implementation as well as `test.containers()` in the `yaml` definition of my `kubernetes` agent. `test.containers()` returns a `String`.

Now `test_extension` is already executed after `test.containers()` is invoked during agent creation.

In my understanding the conditional `@AfterStep` should be executed after the invokation of `call` which is equal to `test()` in the declarative pipeline in the governance Jenkins file.

If I use a multi-method pipeline by renaming `void call()` to `void build()` and call `test.build()` rather than `test()` in Jenkinsfile `text_extension` is called after `test`, however I have no idea how JTE decides that since it doesn't know that `void build` is the main template function whereas `containers` is just a helper and if it knew why doesn't it work with a `void call()` step implementation?

### Steps to Reproduce

1. Create a governance tier project with a declarative pipeline calling `test()` and implement the step `test`
2. Create a project using the governance tier and hook in `test_extension` with conditional `@AfterStep`

**Comment by steven-terrana** [comment]
Thanks for reporting @krichter722. 

PR #275 adds a `hookContext.methodName` so that you can filter hooks based on the name of the method that was invoked within the step.
