### ISSUE TITLE
[Bug]: Validation of Libraray parameters of type List is not documented

### ISSUE THREAD

**Issue by krichter722** [jenkinsci/templating-engine-plugin#226]
### Jenkins Version

2.314

### JTE Version

2.3

### Bug Description

As of https://github.com/jenkinsci/templating-engine-plugin/issues/53 `List` is supported as library parameter type, however this is not mentioned [in the docs](https://boozallen.github.io/sdp-docs/jte/2.2.2/library-development/parameterizing_libraries.html)

### Steps to Reproduce

./.

**Comment by cokieffebah** [comment]
updated in the latest docs: https://jenkinsci.github.io/templating-engine-plugin/2.3/

**Comment by krichter722** [comment]
@cokieffebah I don't find any mention of list in https://jenkinsci.github.io/templating-engine-plugin/2.3/reference/library-configuration-schema/.

**Comment by cokieffebah** [comment]
Thanks.  reopening

**Comment by cokieffebah** [comment]
https://jenkinsci.github.io/templating-engine-plugin/2.3/reference/library-configuration-schema/
