### ISSUE TITLE
[Bug]: Support spread operator

### ISSUE THREAD

**Issue by krichter722** [jenkinsci/templating-engine-plugin#227]
### Jenkins Version

2.314

### JTE Version

2.3

### Bug Description

Using the spread operator `*` when calling a varargs Groovy method fails due to

```
00:00:28.440  WorkflowScript: 20: spread not yet supported for CPS transformation @ line 20, column 25.
```

The message suggests that this call is supposed to be supported one day.

### Steps to Reproduce

Call a varargs method

```
def method(String... values) {
    // ...
}
```

with spread operator

```
libraryClass.method(*config.configValues)
```

**Comment by psig-bah** [comment]
appears related to [Jenkins-46163](https://issues.jenkins.io/browse/JENKINS-46163)
message is getting thrown by:
[CpsTransformer.java](https://github.com/cloudbees/groovy-cps/blob/master/lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java) from the [cloudbees/groovy-cps project](https://github.com/cloudbees/groovy-cps) 
which is used by the [Pipeline: Groovy](https://plugins.jenkins.io/workflow-cps/) plugin

**Comment by cokieffebah** [comment]
closing as this issue is at the Jenkins level and not specific to our plugin
