### ISSUE TITLE
Is it possible to use JTE for declarative pipelines?

### ISSUE THREAD

**Issue by tkgreg** [jenkinsci/templating-engine-plugin#23]

**Comment by JugurthaT** [comment]
Have you found an answer for this?

**Comment by steven-terrana** [comment]
Hello @tkgreg and @JugurthaT - we have not extensively tested the use of the declarative syntax.  as of now, it is not supported. 

The issue is that declarative syntax expects to know what's going to happen before the pipeline runs, or be able to lookup steps that are contributed by regular jenkins shared libraries. 

Due to the runtime composition of pipelines with JTE, they aren't natively compatible.  

You could probably make your template a declarative pipeline and invoke steps from within a ``script`` block. 

It might also be possible to use declarative syntax from within an individual library step but i have not tested this.

**Comment by Hokwang** [comment]
@steven-terrana is there updates? did you test declarative syntax or do you have a plan for support?

**Comment by steven-terrana** [comment]
i have not tested JTE with declarative syntax. 

I would love to be able to support but as of right now i'm not sure if it's even possible. 

Currently working on a 2.0 release of JTE and can add declarative support as something I can at least look into. 

no promises though :)

**Comment by tkgreg** [comment]
Can we take a look at the roadmap? :)

**Comment by steven-terrana** [comment]
i'm putting it together right now and i'll post a link at some point today on this issue! 

give me an hour or so :)

**Comment by steven-terrana** [comment]
@tkgreg here ya go!

https://github.com/jenkinsci/templating-engine-plugin/blob/2.0/Version_2.adoc

**Comment by Hokwang** [comment]
@steven-terrana 
I use below pipeline in most of cases.

```
pipeline {
	options {
		buildDiscarder(logRotator(daysToKeepStr: '90'))
		skipDefaultCheckout()
		timeout(time: 1, unit: 'HOURS')
		parallelsAlwaysFailFast()
		ansiColor('xterm')
// can vary 
	}
	
	triggers {
		pollSCM("* * * * *")
	}
	
	agent {
		kubernetes {
			yaml '''
// can vary for project or container
'''
		}
	}
	
	environment {
		// can vary
	}
	
	stages {
		stage('Sync') {
			steps {
				container(name: 'rhel7') { // name can vary
					checkout perforce(
                                        // can vary
					)
				}
			}
		}
		
		stage('Compile') {
			steps {
				container(name: 'rhel7', shell: '/bin/bash') { // can vary
					sh """
                                       // can vary
					"""
				}
			}
		}
		
		stage('Build Docker Image') {
			steps {
				container ('docker') {
					withCredentials([usernamePassword(credentialsId: "$DOCKER_REGISTRY_CREDENTIAL", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
						sh """
					       // maybe same 
						"""
					}
				}
			}
		}
		
		stage('Push Docker Image') {
			steps {
				container ('docker') {
					withCredentials([usernamePassword(credentialsId: "$DOCKER_REGISTRY_CREDENTIAL", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
						sh """
					      // maybe same
						"""
					}
				}
			}
		}
	}
	
	post {
		always {
			cleanup true
                       // can vary
		}
	}
}
```

In my org case,
I want to make/use template for
agent kubernetes syntax, (and env, options...)
each stages for project or container
and I want to declarative syntax.

Yet I didn't use template engine so don't know how it works and can be work for my thinkging
but I want to let you know this feature request.

Thanks,

**Comment by steven-terrana** [comment]
This functionality has been completed as part of #109 and an upstream PR in the declarative syntax plugin as part of corresponding pull request on https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/403. 

This will be a part of the 2.0 release.
