### ISSUE TITLE
Plugin does not respect Git Refspec

### ISSUE THREAD

**Issue by Eluetkehans** [jenkinsci/templating-engine-plugin#24]
When changing the Refspec in the advanced features of the Repositories section for Git, the refspec always reverts to `+refs/heads/*:refs/remotes/origin/*`, making it impossible to checkout tags.

Plugin Parameters:
<img width="1124" alt="Screen Shot 2019-09-19 at 3 21 44 PM" src="https://user-images.githubusercontent.com/12467126/65274521-77990000-daf1-11e9-9966-89e710fb0804.png">

Actual:
<img width="922" alt="Screen Shot 2019-09-19 at 3 26 58 PM" src="https://user-images.githubusercontent.com/12467126/65274695-f2621b00-daf1-11e9-988c-56f7edb021ef.png">

Expected:
The expected git command `git fetch --tags --progress --prune -- origin +refs/tags/v0.0.1:refs/remotes/origin/tags/v0.0.1` returns successfully from local

**Comment by steven-terrana** [comment]
We have experienced similar problems and believe it has to do with the Git SCM Plugin since we just invoke their functionality and dont' do any checkouts of code directly. 

I will investigate deeper today and report back!  Will likely involve an issue against that plugin and will update when it's created, if that ends up being necessary.

**Comment by steven-terrana** [comment]
as it currently stands,  we only support SCM's that support the SCM API 2.0. 

The git plugin supports this API under specific conditions:

https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/jenkins/plugins/git/GitSCMFileSystem.java#L254-L262

Unfortunately, one of these conditions is that the SCM API 2.0 implementation does not support tags, based on the value of the constant they're using: 
https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/lib/Constants.java#L255 

We will try to address this with the Git SCM Plugin

**Comment by steven-terrana** [comment]
https://github.com/jenkinsci/git-plugin/pull/776

Will update you if this gets merged.  If it does, this problem will be resolved.

**Comment by Eluetkehans** [comment]
Thanks, Steven!

**Comment by steven-terrana** [comment]
The patch to the git-plugin has been merged! 

that ought to resolve this issue.
