### ISSUE TITLE
[feature]: Support versioning and managing configuration as a code

### ISSUE THREAD

**Issue by navrkald** [jenkinsci/templating-engine-plugin#247]
### Feature Description

Hello, I am starting to learn Jenkins Template engine and I would like to ask you it there is way how to version Templates in code?
I mean something similar like in [Jenkins Shared Library versions](https://www.jenkins.io/doc/book/pipeline/shared-libraries/#library-versions) where in `Jenkinsfile` in multi-branch pipeline I can use something like this:
```Jenkinsfile
library identifier: 'libraryName@<git version>', retriever: modernSCM([
    $class: 'GitSCMSource',
    credentialsId: 'someCredentialsId',
    remote: 'https://some-git-provider/someLibraryRepoName.git'
])
```
 where `<git version>` could be branch/commit/git tag, e.g. v1.2.3.
I am asking because this approach allows manage library configuration as a code and allows to possibly use different versions of library in different branches in consumer multi-branch pipeline. The main benefit of this approach is that **breaking change or possible uncaught bug couldn't cause breaking all consumers at the same time** and as when updating to next version it is done via PR which goes via Jenkins CI which helps to catch most of the problems.

As far as I have found right now it is possible to configure Jenkins Templates only via GUI as visible e.g. [here](https://www.jenkins.io/blog/2019/05/09/templating-engine/#step-6-configure-the-governance-tier-in-jenkins)
![alt](https://www.jenkins.io/images/post-images/2019-05-09-templating-engine/governance_tier.png)
 but his not allow to use different version of Template in different branches in multi-branch pipeline or in different repositories in Jenkins organisation folder.
As well this problem with missing versioning was mentioned in [StackOverflow](https://stackoverflow.com/questions/57455061/implementing-versioning-in-jenkins-templating-engine)

Currently missing this feature is blocker for migration from Shared Pipeline Library to Jenkins Templating Engine approach.

**Comment by cokieffebah** [comment]
Yes, from the stackoverflow:
`If you want to have multiple versions of your templates out there and allow teams to upgrade when it's convenient for them, then i would recommend using the pipeline_templates directory capability to have named templates. You could create a different file for each release (i.e., named v1, v2, etc) and then allow teams to choose their template in their configuration files via pipeline_template="v1".`

**Comment by navrkald** [comment]
Thanks @cokieffebah for quick response. I am very well aware of StackOverflow answer but I am not original author of the question and believe workaround mentioned in answer to use for versioning directories instead Version Control System such as Git is huge step back so I have created this issue. Thank you for understanding.

**Comment by cokieffebah** [comment]
understood that you are not the original author, my response was to your initial question: 'Hello, I am starting to learn Jenkins Template engine and I would like to ask you it there is way how to version Templates in code?'
I am not being snarky.  
Seems like you may be asking about versioning for *two* different aspects, Templates (maybe configuration) and, maybe, libraries
are you asking that *each* library have its own SCM repository?
are you asking to version `configuration` (both Template and pipeline configuration file) or just the Template and not the pipeline_config.groovy?

**Comment by navrkald** [comment]
Hello @cokieffebah, I am sorry I am still learning JTE. I will try to be more precise now formulating feature request and will use terminology from [this blogpost](https://www.jenkins.io/blog/2019/05/09/templating-engine/)  step `Step 6: Configure the Governance Tier in Jenkins`. 

Problems with versioning and and Configuration As A Code would solve following: 
Creation of new pipeline step (similar to [library](https://www.jenkins.io/doc/pipeline/steps/workflow-cps-global-lib/#library-load-a-shared-library-on-the-fly)) which can be put to Jenkinsfile, where can be specified both Pipeline Configuration Repository and Library Source repository.

**Comment by cokieffebah** [comment]
I think I get your ask, now.  you want the ability to define library versions in the call in the template like
```
    def lib = library_fetch(lib_name: 'gradle', version/branch: '1.0')
     lib.build()
     lib.unit_test()
```
is this correct?

**Comment by navrkald** [comment]
Kind of. I want to be JTE plugin pipeline compatible. This means the setting visible in Jenkins Job gui should be possible to configure as pipeline step('s) 1:1. The rest of the usage of library will be same.

JTE Configuration in gui:
![image](https://user-images.githubusercontent.com/3267836/143213369-1b8bad3e-2283-4ae9-afd2-369a0ae5b2ba.png)
1:1 equivalent step of JTE Configuration in Jenkinsfile:
```
JTEConfiguration(fromSCM: [
  sourceLocation: [
     ///csmStepConfigurationHere
  ]
  configurationBaseDirectory: "some/dir"
])

JTELibrarySources config in gui:
![image](https://user-images.githubusercontent.com/3267836/143214615-c2c220a2-c88d-44b1-9c1e-9803b4cffef6.png)

1:1 equivalent steps of JTE Configuration in Jenkinsfile:
```
JTELibrarySource(fromSCM: [
  // SCM configuration of library1 here
])
JTELibrarySource(fromSCM: [
  // SCM configuration of library2 here
])
```

As bonus if JTE will be pipeline compatible it can be used for generation of steps pipeline syntax generator like it can be now used for e.g. loading Jenkins Shared Libraries
![image](https://user-images.githubusercontent.com/3267836/143215755-688971f8-327d-4fa0-b15d-adb4d2dd0da9.png)

Found some links how to make plugin pipeline compatible:
https://www.jenkins.io/doc/developer/plugin-development/pipeline-integration/
http://vgaidarji.me/blog/2017/06/22/how-to-use-jenkins-plugins-in-jenkins-pipeline/
https://www.jenkins.io/doc/developer/plugin-development/pipeline-integration/
http://www.matthiassommer.it/programming/jenkins-plugin-as-build-step-and-pipeline-compatible/

**Comment by steven-terrana** [comment]
JTE is not intended to be pipeline compatible and won't be. It's a pipeline development framework that's built _on top of_ the existing Jenkins pipeline scripting engine. 

It's not intended to be invoked from a non-JTE pipeline. 

I would recommend digging into the documentation [here](https://jenkinsci.github.io/templating-engine-plugin/2.3/concepts/framework-overview/overview/). It offers a few different ways to start learning JTE. 

With JTE, the [Pipeline Template](https://jenkinsci.github.io/templating-engine-plugin/2.3/concepts/pipeline-templates/overview/) _is_ the Jenkinsfile. It's just that the pipeline will have access to injected variables, called [Pipeline Primitives](https://jenkinsci.github.io/templating-engine-plugin/2.3/concepts/pipeline-primitives/overview/).

Which variables get injected is based on the aggregated [Pipeline Configuration](https://jenkinsci.github.io/templating-engine-plugin/2.3/concepts/pipeline-configuration/overview/). 

When defining a [Governance Tier](https://jenkinsci.github.io/templating-engine-plugin/2.3/concepts/pipeline-governance/governance-tier/), you achieve versioning by declaring the **branch** of the source code repository to pull from.
