### ISSUE TITLE
[Bug]: java.lang.NoSuchMethodError: No such DSL method 'agent' found among steps with JTE

### ISSUE THREAD

**Issue by satishjs2297** [jenkinsci/templating-engine-plugin#251]
### Jenkins Version

2.235.1

### JTE Version

2.2.2

### Bug Description

Team,  I have created jte pipeline workflow repo with build and deployment stages. I successfully tested this script on jenkins instance (version: 2.263.1) and JTE Version: 2.3 and build was passing on this jenkins (2.263.1) instances.

But when I configured the same pipeline repo on jenkins instance (version: 2.235.1) and JTE Version: 2.2.2 and start the application build, i am getting below error. 

FYI. Both the jenkins instances are using same cloud docker agent templates and these templates are working fine on both the instances for other regular build.

Can you please check and add share your inputs on this ? 

> [JTE] -- file path: global-pipeline-config/Jenkinsfile
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] End of Pipeline
java.lang.NoSuchMethodError: No such DSL method 'agent' found among steps [ArtifactoryGradleBuild, MavenDescriptorStep, addEmbeddableBadgeConfiguration, addInteractivePromotion, archive, artifactoryDistributeBuild,

### Relevant log output

```shell
> [JTE] -- file path: global-pipeline-config/Jenkinsfile
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] End of Pipeline
java.lang.NoSuchMethodError: No such DSL method 'agent' found among steps [ArtifactoryGradleBuild, MavenDescriptorStep, addEmbeddableBadgeConfiguration, addInteractivePromotion, archive, artifactoryDistributeBuild,
```

### Steps to Reproduce

https://www.jenkins.io/blog/2019/05/09/templating-engine/

**Comment by cokieffebah** [comment]
why do you need to use the older version when newer version seemed worked for you?

**Comment by steven-terrana** [comment]
_somewhere_, the pipeline is trying to invoke a step called `agent`. 

It's not finding a JTE primitive (library step or otherwise) called `agent`... so then it would check the available Jenkins DSL pipeline steps. 

It's not finding a step called `agent` there either. 

Could you please share your pipeline template and/or library steps?
