### ISSUE TITLE
[Bug]: The JTE pipeline job cannot load more than 128 files 

### ISSUE THREAD

**Issue by aya-hamed1** [jenkinsci/templating-engine-plugin#256]
### Jenkins Version

2.277.3

### JTE Version

2.3

### Bug Description

the JTE pipeline uses :
Pipeline_configuration and Libraries 
When I used 129 files in my jte pipeline including steps in all read Libraries and pipeline_configuration files [pipeline_config.groovy and pipeline_template files] 
Issue appeared with below error :
[JTE] Cannot cast object '[]' with class 'java.util.LinkedHashSet' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List() 

### Relevant log output

```shell
[JTE] Cannot cast object '[]' with class 'java.util.LinkedHashSet' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List()
```

### Steps to Reproduce

try to use more than 128 files to be loaded in your pipeline

**Comment by steven-terrana** [comment]
thanks for reporting. will look into this.
