### ISSUE TITLE
[Bug]: `instanceof` for library classes is `false` in template and other steps

### ISSUE THREAD

**Issue by steven-terrana** [jenkinsci/templating-engine-plugin#279]
### Jenkins Version

LTS

### JTE Version

2.3

### Bug Description

Instantiations of library provided classes are not recognized outside of the step where they were created.

### Root Cause

After some digging I've identified the root cause of this problem.
The Pipeline Template, and each StepWrapperScript, are compiled with different classloaders.

Pipeline execution begins via [`CpsFlowExecution.start()`](https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java#L512). During `start()`, the Pipeline Template is compiled by a [`CpsGroovyShell`](https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java) created by a [`CpsGroovyShellFactory`](https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShellFactory.java) within [`CpsFlowExecution.parseScript()`](https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java#L556) which results in the normal classloader that's typically used in a Jenkins pipeline.  See [workflow-cps/doc/classloader.md](https://github.com/jenkinsci/workflow-cps-plugin/blob/master/doc/classloader.md) for more info there. 

Each JTE library step is compiled by creating individual mock `CpsFlowExecution` and running `parseScript()`, which follows the same process as above to create the `StepWrapperScript` - resulting in each step having its own classloader. This happens within [`StepWrapperFactory.prepareScript()`](https://github.com/jenkinsci/templating-engine-plugin/blob/main/src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperFactory.groovy#L142).

So far, attempts at creating a common classloader shared by the Pipeline Template and each `StepWrapperScript` have failed - resulting in either compilation errors or serialization errors preventing rehydrating after a restart. 

The compilation errors are coming from the fact that the template and steps require a different [`CompilerConfiguration`](https://github.com/groovy/groovy-core/blob/master/src/main/org/codehaus/groovy/control/CompilerConfiguration.java) which we modify in various [`GroovyShellDecorator`](https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/GroovyShellDecorator.java) extensions  ([`PipelineTemplateCompiler`](https://github.com/jenkinsci/templating-engine-plugin/blob/main/src/main/groovy/org/boozallen/plugins/jte/init/PipelineTemplateCompiler.groovy) and [`StepWrapperShellDecorator`](https://github.com/jenkinsci/templating-engine-plugin/blob/main/src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperFactory.groovy#L183)) and that `CompilerConfiguration` is actually stored on the [`GroovyClassLoader`](https://github.com/groovy/groovy-core/blob/master/src/main/groovy/lang/GroovyClassLoader.java#L78).

### Steps to Reproduce

create a library with a class:
```
class Build implements serializable{}
```

create a step to instantiate a `Build` object:
```
// createBuild.groovy
import Build
Build call(){
  return new Build()
}
```

create another step to check `instanceof`: 
```
// checkBuild.groovy
import Build
void call(def b){
  println b instanceof Build // should be true, but is false
}
```

pipeline template:
```
def b = createBuild()
checkBuild(b)
```

**Comment by cokieffebah** [comment]
what is the class of the instance, at each point
