### ISSUE TITLE
Unable to build the plugin

### ISSUE THREAD

**Issue by Quaiks** [jenkinsci/templating-engine-plugin#29]
Hello!

I am trying to build the plugin locally but I am getting the following error when executing gradle

`> No value has been specified for property 'mainClassName'.`

Any help? Thanks!

**Comment by steven-terrana** [comment]
Hmm.  running ``make jpi`` on the master branch currently builds fine for me. 

What version of gradle do you have locally (gradle -v)? 

**gradle -v**

------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.14.4 x86_64

**Comment by Quaiks** [comment]
Ups! My fault! I was executing `gradle clean build`.  Let's see if I can work on #28
