### ISSUE TITLE
[feature]: Specify Tools

### ISSUE THREAD

**Issue by driverpt** [jenkinsci/templating-engine-plugin#301]
### Feature Description

Be able to specify Jenkins Pipelines Tool information via Libraries

e.g.:

```
pipeline {
        agent any
        tools {
            maven '3.8.5'
            // or gradle '7.1'
            java '11'
            // or go '1.18'
        }
...
}
```

**Comment by steven-terrana** [comment]
this isn't possible. 

JTE doesn't modify the declarative pipeline syntax, which is what would be required. 

You could instead use the scripted pipeline syntax within a library step.

**maven/steps/build.groovy:**
```
void call(){
  tool  type: 'maven', name: '3.8.6'
}
```
