### ISSUE TITLE
[feature]: Facilitate access to a 'remote' file, included in library resources

### ISSUE THREAD

**Issue by jbmestelan** [jenkinsci/templating-engine-plugin#315]
### Feature Description

With the point of JTE being to factor out reusable library steps, it seems logical for a library step to contain and encapsulate the resources it uses: for example, an Ansible playbook, shell script... 

How are JTE users intended to include and access such resources from the libraries? 

The documentation has an [example](https://jenkinsci.github.io/templating-engine-plugin/2.5.2/concepts/library-development/library-resources/) which shows how to load a file as a string in memory, using the method: `resource(String relativePath)`. However, this is not always sufficient, if we want to execute this file, or pass it to a script.

I have implemented the following workaround: copy 'remote' files into the Jenkins workspace, so they can be retrieved at runtime. This is done in a dedicated library step, to be used each time we want to access a file contained in the library's 'resource' directory.
```
Performs a local copy of a remote file, and returns the name of the copied file.
*/
String call(def remotePath) {
    String fileContent = resource(remotePath)
    // Currently, we have chosen to copy the file into the current directory of the workspace.
    String name = sh(script: "basename ${remotePath}", returnStdout: true).trim()
    writeFile(file: name, text: fileContent)
    return name
}
```
This is yet cumbersome, since this script has to be copied with a unique name into each library (since cross-library resource fetching is not allowed). 

So: am I somehow misusing JTE  here, or would JTE users benefit from a mechanism allowing to manipulate a remote file as though it were local to the workspace?

**Comment by steven-terrana** [comment]
libraries were originally intended to be self-sufficient - meaning that they would either:
1. execute scripts / playbooks in their own resources directory
2. allow users to define configuration for where to fetch the remote scripts from

<hr>
Closing this issue - I do not intend to support libraries fetching resources from other libraries.
