### ISSUE TITLE
[Bug]: Documentation url is 404

### ISSUE THREAD

**Issue by mortenn** [jenkinsci/templating-engine-plugin#332]
### Jenkins Version

n/a

### JTE Version

2.5.3

### Bug Description

Clicking the documentation link on the jenkins plugin page or here on github takes me to an address that is 404

### Steps to Reproduce

Try top open docs

**Comment by cokieffebah** [comment]
On https://github.com/jenkinsci/templating-engine-plugin, clicked 
![here](https://github.com/jenkinsci/templating-engine-plugin/assets/23703182/0b6eff89-0a2e-4fa6-b5fe-89406f6dc475)
which lands on github.io and 
![here](https://github.com/jenkinsci/templating-engine-plugin/assets/23703182/4195a871-5625-48cf-9650-dd1bbff9d0c1)
which just stays on the plugin page
