### ISSUE TITLE
GitHub Organization Repository Selection

### ISSUE THREAD

**Issue by karthikjayaraman80** [jenkinsci/templating-engine-plugin#36]
I am applying the JTE template to my GitHub Organization. In the Projects section I have set the Project Recognizer as Jenkins Templating Engine. However, this adds all the repositories in the Organization. Is it possible to only include repositories that contain the pipeline_config.groovy file in the root directory (Similar to selecting only repositories that contain JenkinsFile)?

**Comment by steven-terrana** [comment]
Hello! 

Sorry for the delay. 

This is not currently possible but it could be done by modifying the TemplateBranchProjectFactory to add some more logic to the scm source criteria: 
https://github.com/jenkinsci/templating-engine-plugin/blob/master/src/main/groovy/org/boozallen/plugins/jte/job/TemplateBranchProjectFactory.groovy#L39-L46


you would update that to be more inline with WorkflowBranchProjectFactory: 
https://github.com/jenkinsci/workflow-multibranch-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory.java#L71-L103

ideally, we'd make this an advanced configuration and make it an optional filter.

**Comment by karthikjayaraman80** [comment]
Do we have an update on when this would be released?

**Comment by steven-terrana** [comment]
i'm trying to group a couple bigger changes together but i can release soon.  probably by the end of this week or next week.

**Comment by slowr** [comment]
just came across this issue as well. thanks a lot for working on this :tada:

**Comment by steven-terrana** [comment]
Just released! 

https://github.com/jenkinsci/templating-engine-plugin/releases/tag/1.6
