### ISSUE TITLE
Allow to specify the Pipeline Configuration directly in the Jenkins UI in the Folder Configuration

### ISSUE THREAD

**Issue by snahider** [jenkinsci/templating-engine-plugin#41]
I my organization the jobs of each team are organized around Folders and each team use a different Pipeline Configuration, we have the same configuration between all jobs of team but different configuration between teams. Currently we have a different pipeline configuration repository for each team and we pass these repositories in the Pipeline Configuration of each Folder.

The request is allow to pass a closure in the Pipeline Configuration of the Folder in order to reduce complexity of managing the configuration, we think that having the configuration in a SCM add a extra layer of complexity without to much benefit in our case.

**Comment by steven-terrana** [comment]
Thanks for the feedback @snahider!  It would be good to add an extension for allowing multiple Pipeline Configuration providers instead of just SCM.   

Will look into this as time allows.
