### ISSUE TITLE
Need help in adding Build parameters to Jenkins Template Engine

### ISSUE THREAD

**Issue by nilave** [jenkinsci/templating-engine-plugin#43]
We are using dynamic build parameters in our pipeline script with old Jenkinsfile way. With Jenkins Template Engine , I'm not able to add build parameters in the Template Engine. Please help.

**Comment by steven-terrana** [comment]
hey @nilave - do you have a reproducible example of what you're trying to do? 

Pipeline templates get executed just like a regular Jenkinsfile, so you should be able to access the build parameters in your template the same way you would the old way.

**Comment by nilave** [comment]
Hi @steven-terrana , thanks for your reply . 

In declarative Pipelines , I was able to define the build parameters using the parameters tag as below

```
  pipeline {
    agent any
         parameters {
      
       string description: 'Build Number to Rollback', name: 'Buildnumber', defaultValue: "default", trim: false
       booleanParam defaultValue: false, description: 'Rollback', name: 'Rollback'
       string defaultValue: config.Version, description: '', name: 'Version'
    }
```

Now moving to JTE , I'm looking for a similar approach either in Template, or in config or in groovy implementation. I tried below way in template file but it doesnt recognize the parameters.

```
parameters {      
       string description: 'Build Number to Rollback', name: 'Buildnumber', defaultValue: "default", trim: false
       booleanParam defaultValue: false, description: 'Rollback', name: 'Rollback'
       string defaultValue: config.Version, description: '', name: 'Version'
}
checkout()
build()
static_code_analysis()
artifactory()
deploy_to dev  
deploy_to prod 
```
Please help.

**Comment by nilave** [comment]
@steven-terrana , please let me know if you had a chance to check this

**Comment by steven-terrana** [comment]
@nilave - when moving to scripted pipeline the syntax changes slightly for declaring parameters. 

```
properties([
    parameters([
        string(defaultValue: 'default', description: 'Build Number to Rollback', name: 'Buildnumber', trim: false), 
        booleanParam(defaultValue: false, description: 'Rollback', name: 'Rollback'), 
        string(defaultValue: '11', description: '', name: 'Version', trim: false)
    ])
])

checkout()
build()
static_code_analysis()
artifactory()
deploy_to dev  
deploy_to prod 
```

works as expected

**Comment by nilave** [comment]
@steven-terrana .. this works like a charm. Thanks for your help!

**Comment by AbhiramSiripurapu** [comment]
The way I have solved this is by creating a new file inside the application repository called parameters.groovy with something like this 
`public inputParameters() {
    def parameters = [
            string(name: 'aws_region', defaultValue: "us-east-1"),
            choice(name: 'environment', choices: "dev\nqa\nprod")
    ]
    return parameters
}

return this;`

Now, I have created a new library with a step loadparameters.groovy which includes the following
`void call() {
    stage("Load Input Params"){
        def params = load "parameters.groovy"
        properties([
            parameters ( params.inputParameters() )
        ])
    }
}`

So this gives us the flexibility to let the application developers compose their own input parameters but also use a single Jenkinsfile that we host inside the governance repo. Now your jenkinsfile will look something like this,
`
node{
    checkout scm
    load_parameters()
    build()
    deploy()
}
`

**Comment by slowr** [comment]
I had some issues on how to define parameters that are library specific and this issue helped me to come up with the following solution.

- Create a library called `parameters` and put inside these two files:

`load_parameters.groovy`
```
def call() {
    properties([parameters(additionalParams)])
}
```

`parameters_validate.groovy`
```
@Validate
void call(context){
    // define library configuration parameters
    String error_msg = """
    The parameters library needs keyword additionalParams to be defined in Jenkins Template:
        keywords{
            additionalParams = []
        }
    """
    try {
        additionalParams.getClass()
    } catch (exc) {
        error error_msg
    }
}
```

- Then, in pipeline configuration I added a keyword that will store the parameters:

`pipeline_config.groovy`
```
...
keywords{
    additionalParams = []
}
...
```

- And lastly, on each library that I want to add parameters I added an init hook that appends the parameter on the keyword that we created above. For example, for artifactory library I have:

`artifactory_start.groovy`
```
@Init
void call(context) {
    additionalParams << booleanParam(name: 'PUSH_RELEASE_ARTIFACTS', defaultValue: false, description: 'Deploy to release repository')
}
```

**Comment by steven-terrana** [comment]
that's a great pattern! 

in my own set of libraries, we call that `artifactory_start` a library **constructor** that has the opportunity to define parameters and initialize any pipeline-wide environment variables. 

Thank you for sharing! 

Please feel free to join the [Gitter Channel](https://gitter.im/jenkinsci/templating-engine-plugin) or share your use case with the community via our [ADOPTERS](https://github.com/jenkinsci/templating-engine-plugin/blob/master/docs/modules/ROOT/pages/ADOPTERS.adoc) file.

**Comment by Ranjitheyy** [comment]
Hi @steven-terrana @slowr @abhiramsiripurapu 

I'm using a Multi branch pipeline concept in my project, in which the parameters are not able to set when pipeline_config.groovy is present in the same path as Jenkinsfile. Any solutions that I can get rid of this issue?

**Comment by steven-terrana-bah** [comment]
can you share the contents of your `pipeline_config.groovy` file?

have you defined any Governance Tier settings? For example, configured the Jenkins Templating Engine portion of Multibranch Project?

**Comment by Ranjitheyy** [comment]
No, not mentioning anything regarding Multibranch, just loading the libraries that are specific for each components.

`allow_scm_jenkinsfile = false


libraries{
	git{
		
	}
	
	docker{
	
	}
	
	argocd{

	}
	slack
	
	{
		
		
	}
	
	validateuser

}`
