### ISSUE TITLE
Library Validation: support Arrays

### ISSUE THREAD

**Issue by steven-terrana** [jenkinsci/templating-engine-plugin#53]
Currently unable to validate a library configuration is of the type ArrayList because it intersects with how enumerations are validated. 

The following test case resulted in a warning: 

``[JTE] Library Validator: Not sure how to handle value class java.util.ArrayList with class class java.lang.Class``

library_config.groovy: 
~~~
fields{
  required{
    someField = ArrayList
  }
}
~~~

pipeline_config.groovy: 
~~~
libraries{
  someLibrary{
    someField = [ "a", "b", "c" ] 
  }
}
~~~

**Comment by SHoar** [comment]
Bumping this -- I'm able to have the validation work on ArrayList, but I would actually prefer to give specific type, i.e. ArrayList<String> or ArrayList<Integer>
