### ISSUE TITLE
Context class hudson.FilePath is missing on @CleanUp

### ISSUE THREAD

**Issue by straurob** [jenkinsci/templating-engine-plugin#60]
As suggested in [this message on Gitter](https://gitter.im/jenkinsci/templating-engine-plugin?at=5e866f9e391cdd3dd4b43edb) I wrapped my template steps in a `node` statement to make sure that all steps run on the same node.

**Jenkinsfile**

```
node {
    build()
    publish_image()
    cleanup()
}
```

The `cleanup()` step is basically just this:

**cleanup.groovy**

```
@CleanUp
void call(context) {
    cleanWs()
}
```

When running this pipeline I get the following error:

```
[Pipeline] // node
[JTE] [@CleanUp - common/cleanup.call]
[Pipeline] cleanWs
Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
Perhaps you forgot to surround the code with a step that provides this, such as: node
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
```

When wrapping the `cleanWs()` in a `node` then the pipeline finishes successfully but then it might happen that cleanWs() is running on a different node.

**Comment by steven-terrana** [comment]
you probably want to just remove the `@CleanUp` annotation if you're going to do it that way. 

Steps annotated with `@CleanUp` get automatically executed after the template is finished executing.
