### ISSUE TITLE
Execute the pipeline in a Jenkins Slave (AWS ECS EC2 based docker)

### ISSUE THREAD

**Issue by sumeshsudhakr** [jenkinsci/templating-engine-plugin#69]
I tried the JTE and it's working fine in my Master.

How can I specify to run the entire pipeline in a Jeknins slave ?

So that, the code checkout, build , test and deploy etc should be executed in Jenkins Slave (Docker)
I am using AWS ECS -EC2 based containers as my Jenkins slave. So when each job invoked, it will spin-up a docker container, execute every stages and once completed, the slave will be terminated.
 
In my declarative pipeline I used "agent {label 'ec2-jenkins-slave'}" for that. So the code checkout, build test etc are happened in a Jenkins Slave Docker container.

But in JTE, I couldn't implement it successfully.

I tried  the following in my each library

node("my-docker-agent-name"){
--- my commannds---
}

but it ended-up with creating new docker slaved on each steps. Also I coudn't see the source code in the new containers.

So I changed back the libraries in the following format

node{
--- my commannds---
}

and tried, the following in the Jenkins file

node("ec2-jenkins-slave")
{
build()
test()
deploy()
}

Which ended up in creating a new docker container and add the stages executed in my Jenkins MASTER

Can you tell me how can I implement JTE to execute all steps in a Jenkins slave So that, when I trigger the job, the code pull, build, test, deployment trigger etc should be executed in a single container

-----------------------------------------------------------------------------------------
My Files ( used  for Testing)

pipeline-configuration/Jenkinsfile

`node("ec2-jenkins-slave")
{
build()
s3push()
}`

Pipeline Config file
pipeline-configuration/pipeline_config.groovy

`libraries{
    docker
    s3
    }`

Test library for docker
docker/build.groovy

`def call(){
   stage "Building Docker Image", {
   println "Building Docker Image"
  }
node{
       sh "docker build -t test:test ."
       login_to_registry()
       sh """
       echo 'hostname' ; \
       hostname ; \
       docker tag  'test:test' '2xxxxxx8.dkr.ecr.us-east-2.amazonaws.com/myexp:${BUILD_NUMBER}' ; \
       docker push '2xxxxxxxx8.dkr.ecr.us-east-2.amazonaws.com/myexp:${BUILD_NUMBER}'
       """
       
}
}`

Test library for S3
S3/s3push.groovy

`def call(){
   stage "Pushing Artifacts to S3", {
   println "Push Artifacts to S3"
   }
node{
       sh """
       aws s3 cp test.zip s3://myexps3/

       """
       
}
}`

**Comment by steven-terrana** [comment]
Hello, the issue was caused by the fact that JTE used to make calls to `node` blocks during initialization, before executing the template, without passing a node label. 

This often resulted in JTE hanging for users that were leveraging Cloud plugins or needed agent-specific selection for all node blocks. 

The PR goes into more detail.

This was removed in [JTE 1.7](https://github.com/jenkinsci/templating-engine-plugin/releases/tag/1.7)
