### ISSUE TITLE
Guidance on Multibranch Pipelines

### ISSUE THREAD

**Issue by DuckieHo** [jenkinsci/templating-engine-plugin#71]
With a multibranch or Github/Bitbucket project type, a single Jenkinsfile is usually the entry point for all Jenkins execution.  Combined with templates, the benefit is a single scheme can be applied to many projects.  The challenge is each branch, repo, or event may be expected to follow a different pipeline.  Generally, the approach is to have filtering/routing logic in the initial Jenkinsfile and then load the applicable pipelines/methods.  There are some opinionated approaches to accomplish this:
- **Jenkins Pipeline - Load:** https://www.jenkins.io/doc/pipeline/steps/workflow-cps/#load-evaluate-a-groovy-source-file-into-the-pipeline-script
- **Templates via Shared Library:** https://www.jenkins.io/blog/2017/10/02/pipeline-templates-with-shared-libraries/

---
What is JTE's opinion on _per-branch_, _per-repo_, or _per-event_ pipelines?  Is there a JTE recommended way?

**Comment by steven-terrana** [comment]
As an unopinionated framework, JTE does not have any mechanism to do this.  

That being said, Booz Allen's SDP Pipeline Libraries have `github` and `gitlab` libraries that implement this type of functionality. 

These libraries provide helpful wrappers for doing business logic routing based upon what exactly is happening in the SCM. 

The steps are `on_pull_request`, `on_change`,  `on_commit`, and `on_merge`. 

In combination with JTE's Keywords functionality to create template variables that are regular expression, we use these libraries to create templates that look like: 

```
on_commit to: feature, {
  // code that runs only on commits to a feature branch
}

on_pull_request to: develop, {
  // code that runs only on pull requests to a development branch
}

on_merge to: develop, {
  // code that runs when a PR is merged into the development branch
}

on_pull_request to: master, from: develop, {
  // code that runs only on PR to master from develop 
}

on_merge to: master, {
  // code that only runs on merge to master 
}
```

in the above: `feature`, `develop`, and `master` are JTE Keywords that map to regular expression: 

```
keywords{
    master  =  /^[Mm]aster$/
    develop =  /^[Dd]evelop(ment|er|)$/ 
    feature = /^feature-.*$/
    hotfix  =  /^[Hh]ot[Ff]ix-/ 
    release =  /^[Rr]elease-(\d+.)*\d$/
}
```

A similar pattern could be used for other types of events. 

The [SDP Libraries Documentation](https://boozallen.github.io/sdp-docs/sdp-libraries/2/index.html) and [Repository](https://github.com/boozallen/sdp-libraries).

**Comment by DuckieHo** [comment]
Thanks Steve, I am far more clear on the intended implementation now!

The samples in the SDP libraries were the key to grasping the concepts.
