### ISSUE TITLE
Unable to call a step - that takes an application_environment object as a param - from stage block

### ISSUE THREAD

**Issue by Vince-Cercury** [jenkinsci/templating-engine-plugin#72]
In my pipeline_config:

```
application_environments{
    dev{
        long_name = "Development"
    }
    prod{
        long_name = "Production"
    }
}
```

I've got a step called `project_specific_step.groovy`:
```
void call(environment) {
   echo "environment.short_name: ${environment.short_name}"
}
```

### Calling it from Jenkinsfile:
```
project_specific_step dev
```

OUTPUT: 
```
environment.short_name: dev
```

As expected

### Calling it from a stage block defined in pipeline_config.groovy:

```
stages{
  stage_do_things{
    project_specific_step dev
    common_step_a
    common_step_b
  }
}
```

OUTPUT: 
```
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: org.boozallen.plugins.jte.binding.injectors.ApplicationEnvironment.call() is applicable for argument types: () values: []
Possible solutions: wait(), any(), wait(long), any(groovy.lang.Closure), each(groovy.lang.Closure), wait(long, int)
```

Error.

Is passing an application_environment object to a step supported from a stage block?

Use case: Only one of my project need to call project_specific_step step. The others don't. I want to reuse the same Jenkinsfile though. I don't want to have to create another Jenkinsfile just for that one project that is different. So overriding a stage block primitive in pipeline_config of this specific project is ideal.
However my step needs an input, as it is being called a few times, in different stages. Behaviour will change depending on the environment we pass

Suggestions please?

**Comment by steven-terrana** [comment]
Recapping the conversation from the JTE Gitter Channel: 

Stage parameters should be passed from the pipeline template and accessed in steps via the `stageContext` variable. 

This `stageContext` functionality has been documented as part of the 2.0 release.
