### ISSUE TITLE
"Exclude repository branches without a pipeline configuration file" seems to be broken

### ISSUE THREAD

**Issue by OnePointLine** [jenkinsci/templating-engine-plugin#76]
Hi,

I was going through the article https://www.jenkins.io/blog/2019/05/09/templating-engine/ and I've used repositories in the article to at least make it discover repositories with pipeline_config.groovy but failed.

First of all, I have tested the same this twice on Jenkins 2.222.3 and on 2,199, JTE plugin version 1.7 for both cases. 

So steps to reproduce are pretty simple:

1. I created forks of library, configuration and gradle app repo from the article repo in my gitHub org.
2. Added a Github organization pipeline with the default behavior - discover branches, pull requests, PR from forks, 
3. "Project recognizers" is JTE, I checked "Exclude repository branches without a pipeline configuration file"
4. I scan a repo and I can see in the logs the same error for each branch it discovers:

> Proposing example-jte-app-gradle
> Examining JTE-sample/example-jte-app-gradle
> 
>   Checking branches...
> 
>   Getting remote branches...
> 
>     Checking branch master
> 
>   Getting remote pull requests...
> ERROR: Failed to create or update a subproject example-jte-app-gradle
> groovy.lang.MissingPropertyException: No such property: ScmPipelineConfigurationProvider for class: org.boozallen.plugins.jte.job.TemplateBranchProjectFactory
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
> 	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.callGroovyObjectGetProperty(GetEffectivePogoPropertySite.java:70)
> 	at org.boozallen.plugins.jte.job.TemplateBranchProjectFactory$1.isHead(TemplateBranchProjectFactory.groovy:71)
> 	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:342)
> 	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:249)
> 	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:1000)
> 	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
> 	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:327)
> 	at jenkins.branch.MultiBranchProjectFactory$BySCMSourceCriteria.recognizes(MultiBranchProjectFactory.java:261)
> 	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.recognizes(OrganizationFolder.java:1407)
> 	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.complete(OrganizationFolder.java:1422)
> 	at jenkins.scm.api.trait.SCMNavigatorRequest.process(SCMNavigatorRequest.java:254)
> 	at jenkins.scm.api.trait.SCMNavigatorRequest.process(SCMNavigatorRequest.java:204)
> 	at org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator.visitSources(GitHubSCMNavigator.java:996)
> 	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:490)
> 	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
> 	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
> 	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:971)
> 	at hudson.model.ResourceController.execute(ResourceController.java:97)
> 	at hudson.model.Executor.run(Executor.java:428)
> 12:57:51 4 repositories were processed
> [Wed Apr 29 12:57:51 CEST 2020] Finished organization scan. Scan took 7 sec
> 

Considering that file is pipline_config.groovy is present, I expect the repo to be discovered. 
Could you please advise what I'm doing wrong?  

Thank you

**Comment by steven-terrana** [comment]
hey!  you're not doing anything wrong.

this was a mistake on our part and has been patched https://github.com/jenkinsci/templating-engine-plugin/pull/75

a new release will be out tonight that patches the problem.

**Comment by steven-terrana** [comment]
https://github.com/jenkinsci/templating-engine-plugin/releases/tag/1.7.1

should resolve.  if your issues persists after upgrading, please let us know!
