### ISSUE TITLE
Expand initialization logging so that each injector logs what it is injecting 

### ISSUE THREAD

**Issue by steven-terrana** [jenkinsci/templating-engine-plugin#84]
Currently logging for JTE initialization is all over the place. 

The idea for this issue would be to leverage `TemplateLogger` in every `TemplatePrimitiveInjector` so that we log each primitive JTE creates and makes accessible to the pipeline template during runtime

**Comment by steven-terrana** [comment]
post injection - print a warning if a primitive has been created that overrides a `GlobalVariable` or a Jenkins pipeline step.

Reuse logic from [InvokeMethod](https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java#L108-L118) and [Here](https://github.com/jenkinsci/workflow-cps-plugin/blob/a86a2c43356f35b345023a48d7ac4ceee0f231f5/src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java#L162-L171)

**Comment by cokieffebah** [comment]
Update TemplateBinding.lock() to invoke namespace.printAllPrimitives on each namespace. instead of logging on each add of the primitive

**Comment by cokieffebah** [comment]
done in the namespace work
