### ISSUE TITLE
New 'Exclude branches without a pipeline configuration file' doesnt allow setting 'Configuration Base Directory'

### ISSUE THREAD

**Issue by andrewkro** [jenkinsci/templating-engine-plugin#96]
Jenkins: 2.204
JTE Plugin: 1.7.1

[#52](https://github.com/jenkinsci/templating-engine-plugin/pull/52) Introduced a feature to skip branches that do not include a pipeline configuration file.

Currently it is only supported to be in root, even though the baseDir setting is available under 'Configuration Base Directory'

We currently use 'Configuration Base Directory' to store multiple templates in a single repository, and cannot enable this yet as it will skip branches that DO include a config file (under baseDir)

**Comment by steven-terrana** [comment]
The checkbox to skip branches that do not include a pipeline configuration file is referring to the repository level `pipeline_config.groovy` which currently must live at the root of the repository. 

If a Configuration Base Directory is being set, then that would be for a Governance Tier and this filtering does not currently apply for that use case. 

Could you describe your use case more and what you're trying to accomplish with JTE?

**Comment by steven-terrana** [comment]
stale issue, feel free to reopen if necessary
